services:
  db:
    image: postgres:15-alpine
    container_name: meu_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: ticketmaster

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:7.4-alpine
    container_name: meu_redis
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning --requirepass admin@123
    volumes:
      - cache:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production

    container_name: ticket_master_api
    restart: unless-stopped

    depends_on:
      - db
      - cache

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production

    env_file:
      - .env.production.local

volumes:
  cache:
    driver: local
  postgres_data: